version: 2
jobs:
  build:
    working_directory: ~/ft-six-degrees-be-app
    docker:
      - image: node:6
        environment:
          CI: true
    steps:
      - checkout
      - run:
          name: Change permissions on files
          command: |
            chmod +x ./_scripts/push_to_staging.sh
            chmod +x ./_scripts/run_tests.sh
      - run:
          name: Run tests
          command: sh ./_scripts/run_tests.sh
  deploy:
    machine:
      enable: true
    working_directory: ~/ft-six-degrees-be-app
    steps:
      - checkout
      - run:
          command: sh ./_scripts/push_to_staging.sh
workflows:
  version: 2
  test-project:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
